### ISSUE TITLE
[NIP10]: Reward node operator, reduced cold staking reward for coin holder

### ISSUE THREAD

**Issue by MarkSamson** [NeblioTeam/Neblio-Improvement-Proposals#10]
### Proposal Description

I’m submitting this proposal regarding the current staking rewards after a discussion about this topic on Telegram. Currently there is a staking reward of 10% for the holder of the coins when they stake them either on there own node or when they delegate, cold stake, them to another node operator. I think this should be changed, that’s the reason for this proposal.

I think it would be beneficial for the network if we get more nodes online, this makes the network stronger. One of the ways to accomplish this is to make it more attractive to host one. The person that is staking on someone else his node isn’t providing any value to the network by confirming transactions. The people that delegate there coins using the cold staking feature of the network should pay a percentage of 2% to the owner of the node and should only be rewarded with the remaining 8% themselves. This way more people will be motivated to host their own node, and motivates node owners to recruit new cold stakers for there node.

I think the 80%/20% split is reasonable because for the people that find it to much of a hastle to setup a node can still make use of the great feature and generate a passive income. Next to that I think that 2% is still a good enough reward for providing the node.  But if people have another idea please comment it.

**Summary**
The rewards of coins that are delegated/staked cold should be split up, 2% to the node owner and 8% to the owner of the coins. This gives people a reason to host there own node instead of delegating it to someone else. More nodes means a stronger network. 

### Proposal Voting Details

The voting period should be 30 days.

### Other Information

None

**Comment by NeblioTeam** [comment]
Thanks for submitting this proposal! 

@TheQuantumPhysicist wrote our Cold Staking code, Sam could you chime in on how big of a change it would be to split the stake reward between the owner and staker address? I seem to remember we discussed this long ago when we were planning the development of Cold Staking, but decided against adding it for Cold Staking 1.0.

@MarkSamson Why a 7/3 split? Personally, I would likely support this proposal, however I'd like to hear feedback on the 7/3 split vs other options. Why not 9/1, 8/2, or even 5/5? 

If anyone else has thoughts around this proposal, please post them.

**Comment by MarkSamson** [comment]
@NeblioTeam Thanks for asking, should have included the 7/3 reasoning inside of the post. I have updated the post.
In my opinion the ?/? is debatable here in this topic.

**Comment by fyziktom** [comment]
I think this is good idea to reward nodes a little also. 
7/3 is closer to the nature. Old Jewish rule recommends to split fortune to thirds too and one part put to conservative investment. That's what represents existence of the Neblio network. 
The split to thirds was always better than split to half or famous 8/2. 3% is also usual target for inflation of the central banks (or more 2,5%). I have two friends in this field. I will ask them for a comment. Please wait a little with schedule the voting. I have to reach them. Both are busy guys. It will be great to have their opinion. Thanks 🙏

**Comment by RyanXNeb** [comment]
> ### Proposal Description
> I’m submitting this proposal regarding the current staking rewards after a discussion about this topic on Telegram. Currently there is a staking reward of 10% for the holder of the coins when they stake them either on there own node or when they delegate, cold stake, them to another node operator. I think this should be changed, that’s the reason for this proposal.
> 
> I think it would be beneficial for the network if we get more nodes online, this makes the network stronger. One of the ways to accomplish this is to make it more attractive to host one. The person that is staking on someone else his node isn’t providing any value to the network by confirming transactions. The people that delegate there coins using the cold staking feature of the network should pay a percentage of 3% to the owner of the node and should only be rewarded with the remaining 7% themselves. This way more people will be motivated to host their own node, and motivates node owners to recruit new cold stakers for there node.
> 
> I think the 7/3 split is reasonable because for the people that find it to much of a hastle to setup a node can still make use of the great feature and generate a passive income. Next to that I think that 3% is still a good enough reward for providing the node. But if people have another idea please comment it.
> 
> **Summary** The rewards of coins that are delegated/staked cold should be split up, 3% to the node owner and 7% to the owner of the coins. This gives people a reason to host there own node instead of delegating it to someone else. More nodes means a stronger network.
> 
> ### Proposal Voting Details
> Up to the team
> 
> ### Other Information
> None

I actually really love the idea! Though I think 3% is still a bit much for the node operator. From what I've seen from staking pools on other chains, it's more like 1-2% I've even seen 0.5% If a node gets popular and starts generating even 1-2% from delegators that's still going to be a nice earning, so let's say 1.5-2% for the node operator offering the service, say they have 10 cold stakers and earning 2% from each one, that's still good and still a good chunk for the staker. 

Unless it can be made variable, set by the node operator, who can set their fee between a range of 0.5-3%. data could be up on the Neblio Explorer as a new tab, 'Cold staking services', and each person offering the service, can can view data such as uptime, their fee, number of people cold staking, address to delegate to etc. Perhaps that could be a solution? But otherwise I'd like to see a split 8/2 rather than 7/3.

**Comment by TheQuantumPhysicist** [comment]
> Sam could you chime in on how big of a change it would be to split the stake reward between the owner and staker address? I seem to remember we discussed this long ago when we were planning the development of Cold Staking, but decided against adding it for Cold Staking 1.0.

The primary reason we didn't do this was simplicity in the interest of security. I think it's not impossible. But given that I did the cold-staking protocol a long time ago, I have to look into it again to see the limitations.

**Comment by NeblioTeam** [comment]
> But given that I did the cold-staking protocol a long time ago, I have to look into it again to see the limitations.

When you have the time, please look into this and let us know your findings.

**Comment by MarkSamson** [comment]
Thanks @fyziktom, @RyanXNeb and @TheQuantumPhysicist  for commenting.

@TheQuantumPhysicist looking forward to your findings to see if this is achievable.

@fyziktom thanks for checking with your friends, really interested in what they think about the splitting rate.

**Comment by RyanXNeb** [comment]
I know you guys are busy with Neblio X R&D but any update here @TheQuantumPhysicist ?

**Comment by NeblioTeam** [comment]
I know @TheQuantumPhysicist was recently working on some prototyping in this area to see if this was possible and come up with an effort estimate. It's looking like this will take significant work to do this in a secure way, but I'll let Sam chime in when he completes his assessment.

**Comment by fyziktom** [comment]
> I know you guys are busy with Neblio X R&D but any update here @TheQuantumPhysicist ?

I am in talk with my friends. I explained them some details, but now I have to create for them some block scheme to explain more how I feel about Neblio industrial nodes (those in factories or gov) which will create very strong basic network for the future. It little copies part of the country infrastructure. For example in Czech Republic we have 30% of GDP from industry. Thats why I am focusing to create good tools for industry. They can keep the stable base. Most of the customers who we speak with have projects for 10 or more years. 

So please give a little more time for this. I think that Neblio Team has lots of to do with the Neblio X update, so I hope we have time to think this through :)

**Comment by RyanXNeb** [comment]
> > I know you guys are busy with Neblio X R&D but any update here @TheQuantumPhysicist ?
> 
> I am in talk with my friends. I explained them some details, but now I have to create for them some block scheme to explain more how I feel about Neblio industrial nodes (those in factories or gov) which will create very strong basic network for the future. It little copies part of the country infrastructure. For example in Czech Republic we have 30% of GDP from industry. Thats why I am focusing to create good tools for industry. They can keep the stable base. Most of the customers who we speak with have projects for 10 or more years. 
> 
> So please give a little more time for this. I think that Neblio Team has lots of to do with the Neblio X update, so I hope we have time to think this through :)

Sounds good. Yes Neblio X will be a big undertaking and quantity of work, and more should be clear about what is possible after it's completion.

**Comment by MarkSamson** [comment]
Just to give this a bumb.

@fyziktom did your friends in this field already got a moment to take a lot at this?

And @TheQuantumPhysicist do you already know if this is technically possible?

**Comment by NeblioTeam** [comment]
> And @TheQuantumPhysicist do you already know if this is technically possible?

Sam's priorities have shifted a bit, causing him to temporarily halt the prototyping work he was doing for this as he needed to focus on other things. 

His initial thoughts, based on the progress he made with his prototype, was that it was possible, but was a large amount of work (and would certainly require a mandatory upgrade) and would take a lot of effort to implement securely. 

Due to not knowing when Sam will have time to continue his prototyping work in this area, I think it is fine if we do not hold up the proposal any longer. We are fine to put this to a vote, whenever you are ready @MarkSamson. As the submitter, you just have to officially call for a vote. 

Several Notes:
- This proposal is currently to split the cold staking reward 70%/30%, unless the original proposal above is modified to say otherwise. 
- Submitters (and others that support the proposal) are responsible for spreading the word and gathering support and votes for their proposal. 
- Since you did not provide preferences for the vote schedule, our default is for the vote to last 1 week and start 1 week after the submitter calls for the vote to be scheduled. If you would prefer otherwise, please update your proposal to indicate as such.

**Comment by MarkSamson** [comment]
Thanks for the update @NeblioTeam. Great to hear that the initial thoughts are that it might be possible.

I didn't know that those points where up to me, but i do now. I would like to wait for a response from @fyziktom before I call it for a vote.

**Comment by RyanXNeb** [comment]
> Thanks for the update @NeblioTeam. Great to hear that the initial thoughts are that it might be possible.
> 
> I didn't know that those points where up to me, but i do now. I would like to wait for a response from @fyziktom before I call it for a vote.

Personally I would still be more in favour of say an 80/20 split, with a little more going to the staker than the stake service operator because even at 20% if the stake service can attract a good number of stakers to their service, they would earn a decent amount still. That way stake service can still earn by having a multiple of stakers and stakers still get 80% which again is also going to be a little more attractive to cold stake. So I think overall should be favourable for all parties IMO.

**Comment by fyziktom** [comment]
> Just to give this a bumb.
> 
> @fyziktom did your friends in this field already got a moment to take a lot at this?
> 
> And @TheQuantumPhysicist do you already know if this is technically possible?

Yes, but it is stuck on me. He needs more info and I need to prepare some graphics about it. But I am totally busy lately. I am migrating VEFramework  Blazor apps to .NET 6.0, onboarding couple of teams. And all graphics stuffs are my weakness, so I am trying to find someone who will be able to help me locally. 

I am not sure if it is necessary to do any of these changes. We should focus to adoption. Neblio has enough features for another 5 years of adoption without any change. We need to bring developers who will help to use it. At first point help to finish and improve VEFramework. Without adoption framework like this it is very hard to use blockchains.

**Comment by RyanXNeb** [comment]
> > Just to give this a bumb.
> > 
> > @fyziktom did your friends in this field already got a moment to take a lot at this?
> > 
> > And @TheQuantumPhysicist do you already know if this is technically possible?
> 
> Yes, but it is stuck on me. He needs more info and I need to prepare some graphics about it. But I am totally busy lately. I am migrating VEFramework  Blazor apps to .NET 6.0, onboarding couple of teams. And all graphics stuffs are my weakness, so I am trying to find someone who will be able to help me locally. 
> 
> I am not sure if it is necessary to do any of these changes. We should focus to adoption. Neblio has enough features for another 5 years of adoption without any change. We need to bring developers who will help to use it. At first point help to finish and improve VEFramework. Without adoption framework like this it is very hard to use blockchains.
> 

Good point. Core development and VEFramework development are super important, because we need to start working towards serious adoption. We have some kind of time advantage over some other chains but that wont last too long, so what Tomas says makes sense. 

I guess it can still go to a vote maybe, get added to roadmap if successful and team can add it to the roadmap but will work on it only when it isn't clashing with important core dev work?

**Comment by MarkSamson** [comment]
> > Thanks for the update @NeblioTeam. Great to hear that the initial thoughts are that it might be possible.
> > I didn't know that those points where up to me, but i do now. I would like to wait for a response from @fyziktom before I call it for a vote.
> 
> Personally I would still be more in favour of say an 80/20 split, with a little more going to the staker than the stake service operator because even at 20% if the stake service can attract a good number of stakers to their service, they would earn a decent amount still. That way stake service can still earn by having a multiple of stakers and stakers still get 80% which again is also going to be a little more attractive to cold stake. So I think overall should be favourable for all parties IMO.

I have given it some thought and I am going to agree with you on this Ryan. 



> > Just to give this a bumb.
> > @fyziktom did your friends in this field already got a moment to take a lot at this?
> > And @TheQuantumPhysicist do you already know if this is technically possible?
> 
> Yes, but it is stuck on me. He needs more info and I need to prepare some graphics about it. But I am totally busy lately. I am migrating VEFramework Blazor apps to .NET 6.0, onboarding couple of teams. And all graphics stuffs are my weakness, so I am trying to find someone who will be able to help me locally.
> 
> I am not sure if it is necessary to do any of these changes. We should focus to adoption. Neblio has enough features for another 5 years of adoption without any change. We need to bring developers who will help to use it. At first point help to finish and improve VEFramework. Without adoption framework like this it is very hard to use blockchains.

I agree that adoption is currently the most important aspect of everything, but I don't think it is a smart idea to only focus on adoption. If this vote would be successful not all the focus should go towards this nip ofcourse, but in my opinion there should be a balance.

**Comment by RyanXNeb** [comment]
> 
> 
> 
> > > Thanks for the update @NeblioTeam. Great to hear that the initial thoughts are that it might be possible.
> > > I didn't know that those points where up to me, but i do now. I would like to wait for a response from @fyziktom before I call it for a vote.
> > 
> > Personally I would still be more in favour of say an 80/20 split, with a little more going to the staker than the stake service operator because even at 20% if the stake service can attract a good number of stakers to their service, they would earn a decent amount still. That way stake service can still earn by having a multiple of stakers and stakers still get 80% which again is also going to be a little more attractive to cold stake. So I think overall should be favourable for all parties IMO.
> 
> I have given it some thought and I am going to agree with you on this Ryan. 
> 
> 
> 
> > > Just to give this a bumb.
> > > @fyziktom did your friends in this field already got a moment to take a lot at this?
> > > And @TheQuantumPhysicist do you already know if this is technically possible?
> > 
> > Yes, but it is stuck on me. He needs more info and I need to prepare some graphics about it. But I am totally busy lately. I am migrating VEFramework Blazor apps to .NET 6.0, onboarding couple of teams. And all graphics stuffs are my weakness, so I am trying to find someone who will be able to help me locally.
> > 
> > I am not sure if it is necessary to do any of these changes. We should focus to adoption. Neblio has enough features for another 5 years of adoption without any change. We need to bring developers who will help to use it. At first point help to finish and improve VEFramework. Without adoption framework like this it is very hard to use blockchains.
> 
> I agree that adoption is currently the most important aspect of everything, but I don't think it is a smart idea to only focus on adoption. If this vote would be successful not all the focus should go towards this nip ofcourse, but in my opinion there should be a balance. 

I also agree. I think a successful vote getting through just means it gets added to the roadmap. Team can use their discretion as to what proposal to focus on. Currently they are knee deep in NeblioX development which is understandable, but if this upcoming vote is also successful, then at least it means it's on the cards and will be worked on at some point.

**Comment by NeblioTeam** [comment]
`NIP10` has been scheduled for voting!

Vote Start: Block 3887750 (Approximately Mar 31st 2022)
Vote End: Block 3972455 (Approximately Apr 30th 2022)

If you support `NIP10`, set your Neblio Staking wallets (Neblio Core v3.4.0 or higher required) to vote `1` for proposal ID `10` starting at block `3887750` and ending at block `3972455` now!

Voting progress can be tracked at: https://explorer.nebl.io/voting

**Comment by RasmonT** [comment]
I would agree to this only if node operator could setup their own fee, let's say that I'm using my node just for my wallet and friends(don't want a fee), as my node is server based, I wouldn't like to receive any rewards or rather said NEBL on the server node wallet. So in my case, I would setup a percentage fee of 0%, anyone else could setup 5% fee, or 10%, whatever value they would wanted. The thing is that it should be possible to check which operator(node) has their fee set. I don't think it's good idea to have fixed fee on node operator. However letting operators to choose their fee is for another debate I guess.

**Comment by RasmonT** [comment]
This is not true, even in Solana you have several validators with 0% and people still stake their SOL on node that has commission. In the NEBL you don't have a list of cold staking nodes, even Daz is offering it for free. This proposal to me has sense only if the node operator will be able to adjust his fee, even to 0. Not forcing it like that without option to change.

**Comment by Crypt0daz** [comment]
I agree on the fact some would offer 0% if it’s an option, as i’ve personally offered 0% since the start, and would be happy to continue to do so. 

Despite me offering the service at 0%, take up has been pretty low. I can’t have more than 10 addresses using my node, and i imagine that’s down to less than 5 people 

For the amount of development this sounds like it would need, i personally feel it to be a waste of time for the benefits it would bring. 

It also has tax implications for the nodes, which with volatile prices swings, can be risky.

On that note, for transparency, my node will personally be voting against the proposal as it stands. Despite it meaning extra nebls for me, i just don’t feel it justifies the development cost right now.

**Comment by Shane-Neblio** [comment]
> I would agree to this only if node operator could setup their own fee, let's say that I'm using my node just for my wallet and friends(don't want a fee), as my node is server based, I wouldn't like to receive any rewards or rather said NEBL on the server node wallet. So in my case, I would setup a percentage fee of 0%, anyone else could setup 5% fee, or 10%, whatever value they would wanted. The thing is that it should be possible to check which operator(node) has their fee set. I don't think it's good idea to have fixed fee on node operator. However letting operators to choose their fee is for another debate I guess.

variable is the way i'd go too. but i'm still willing to vote on this 80/20 split just to put it in motion. we can tweak it later with another vote to flip it to variable. 
but currently there is a big hurdle in making any kind of split in the code so lets just get this forward to get the coding put into place.. then we can tweak it via another vote. 

To Neblio team, i suggest you keep the coding open to the possibility of "variable" rate in case we put this to vote later.

**Comment by Shane-Neblio** [comment]
> > I would agree to this only if node operator could setup their own fee, let's say that I'm using my node just for my wallet and friends(don't want a fee), as my node is server based, I wouldn't like to receive any rewards or rather said NEBL on the server node wallet. So in my case, I would setup a percentage fee of 0%, anyone else could setup 5% fee, or 10%, whatever value they would wanted. The thing is that it should be possible to check which operator(node) has their fee set. I don't think it's good idea to have fixed fee on node operator. However letting operators to choose their fee is for another debate I guess.
> 
> I decided to not do that in this proposal because then there only needs to be only 1 person that hosts a node that sets it fee to 0% and all the people that want to cold stake choose that node. By doing this there is probably going to be a few really big staking wallets. That wouldn't be good for the network and for the voting results.
> 
> A workaround would be to just send the 2% to his wallet.

how about for "friends" we want to give a rate cut to, the node operator could be given an option to see all nebl addresses staking to their node & cherry pick certain addresses we don't want their rewards with a simple option of "fee? on/off" toggle.

**Comment by NeblioTeam** [comment]
I don't want to stifle the discussion and brainstorming going on in this thread...

But, I want to make it perfectly clear for voters that when they vote on this proposal, they are voting on the "locked in" details of the proposal, as they were written by @MarkSamson in the first post in this thread on the 24th of March when he officially called for a vote. 

Those details are what is being voted on and only what is being voted on for NIP10.

**Comment by Crypt0daz** [comment]
Hey Shane, sorry i didn't reply to that message. But yeah that would definitely be a good feature i reckon. I imagine a lot of stakers likely stake using their own online node to increase security. So would definitely make things less complicated for them, and allow people to offer it up for free if they chose too. Yes votes are definitely increasing, gonna be close but might actually make the minimum participation at this rate.

**Comment by NeblioTeam** [comment]
Unfortunately NIP10 did not pass the vote. It had 10.3% participation vs the requirement of 20%.
