### ISSUE TITLE
[New NIP]: Get neblio relisted on kucoin

### ISSUE THREAD

**Issue by Pasturelunar** [NeblioTeam/Neblio-Improvement-Proposals#2]
### Proposal Description

We need neblio relisted on kucoin. It’s the best shitcoin exchange going. Muh users. Do eeet Eddy

### Proposal Voting Details

20000

### Other Information

Full sned neblio to the mewn

**Comment by NeblioTeam** [comment]
Please submit serious issues if you would like them to be put to a vote by stakers.
