### ISSUE TITLE
[New NIP]: Do some marketing

### ISSUE THREAD

**Issue by Pasturelunar** [NeblioTeam/Neblio-Improvement-Proposals#3]
### Proposal Description

Any marketing would be great. Hire the marketing legend Yuval back again. He did great for a few months before Mossad wanted him back. 

### Proposal Voting Details

8008135

### Other Information

Yuval we love you

**Comment by NeblioTeam** [comment]
Please submit serious issues if you would like them to be put to a vote by stakers.
